### ISSUE TITLE
Partial image at VGA frame size

### ISSUE THREAD

**Issue by gszakacs** [arkhipenko/esp32-cam-mjpeg-multiclient#5] opened 2020-08-26 20:30 UTC
Hi,
80% of the time, I am connecting only from a single client, still, the camera is only loading partial image and at a relatively slow rate ~7fps. 
I did notice that the performance reduction is related to jpg/mjpg compression. For example: I see a complete image when the picture is "static", and partial picture when the picture is changing (wind blowing leafs). ![partial image](https://user-images.githubusercontent.com/10700953/91351152-ce08c700-e7b5-11ea-9341-8031c1931904.JPG)
I am using 4 esp32 cameras as a motion detection / surveillance system and for now, my workaround to the above problem is to set inspection windows away from the bottom of the frame (where the image is not loading properly), but I am wondering what do you recommend for improving performance (lower frame rate ? smaller frame size ? Thanks

**Comment by arkhipenko** [comment] 2020-08-27 16:16
Try using this instead:
https://github.com/arkhipenko/esp32-mjpeg-multiclient-espcam-drivers/tree/master/esp32-cam-rtos

and lowering the FPS on the camera to 15. I found those settings are the best. 
The partial image was caused by the buffer not being populated fully before it is released to the client for upload, but it should be fixed with the semaphores I implemented. So no idea why it still is happening. Are you on the latest release?

**Closed as completed** 2020-11-11 03:13 UTC
